Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-05, with the labels that each got.

#624 Feature/sentry
  README.md
  config/dev.env.js
  config/prod.env.js
  package.json
  src/main.js
  yarn.lock
Labels: enhancement

#632 Fixed translation list not updating on delete
  src/components/translate/TranslationsList.vue
  src/views/repository/Translations.vue
Labels: bug

#646 Fixed edit example not working
  src/api/v2/evaluate-example.js
  src/components/shared/accordion/EditExample.vue
  src/store/evaluate-example/actions.js
Labels: bug

#653 Develop
  src/api/translate.js
  src/components/quick-test/QuickTest.vue
  src/components/repository/debug/Debug.vue
  src/store/translate/actions.js
  src/views/repository/Translate.vue
Labels: bug, dependencies, enhancement

#661 Feature/new sentence results
  package.json
  src/api/v2/evaluate-example.js
  src/components/repository/repository-evaluate/BaseEvaluateResults.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleItem.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
  src/components/repository/repository-evaluate/results/GraphicsResult.vue
  src/components/repository/repository-evaluate/versions/EvaluateVersionItem.vue
  src/components/shared/accordion/SentenceAccordion.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/router/index.js
  src/store/evaluate-example/actions.js
  src/views/repository/Result.vue
  test/unit/specs/components/repository/repository-evaluate/results/EvaluateResultExampleItem.spec.js
  test/unit/specs/components/repository/repository-evaluate/results/GraphicsResult.spec.js
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleItem.spec.js.snap
  test/unit/specs/components/shared/__snapshots__/SentenceAccordion.spec.js.snap
  yarn.lock
Labels: enhancement, help wanted

#663 Hotfix/results
  src/api/v2/evaluate-example.js
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
  src/store/evaluate-example/actions.js
Labels: Hotfix

#664 Fixed older logs status
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
Labels: Hotfix

#670 Hide label button
  src/components/inputs/EntitiesInput/EntityForm.vue
  test/unit/specs/components/inputs/EntitiesInput/EntitiesInput.spec.js
Labels: visualization

#681 Feature/lighthouse widget
  README.md
  config/dev.env.js
  config/prod.env.js
  index.html
  src/components/form-generator/FormGenerator.vue
  src/components/shared/HelpWidget.vue
  src/utils/plugins/lighthouse.js
Labels: enhancement
