Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-07, with the labels that each got.

#752 Added processing status
  src/components/repository/TrainResponse.vue
  src/locales/en.json
  src/locales/pt_br.json
  test/unit/specs/components/repository/__snapshots__/TrainResponse.spec.js.snap
Labels: enhancement

#753 Fixed allow go to category without form datas
  src/components/repository/CreateRepositoryForm.vue
  test/unit/specs/components/repository/__snapshots__/CreateRepositoryForm.spec.js.snap
Labels: enhancement

#784 Feature/payment tab
  src/api/user.js
  src/components/payment/PaymentForm.vue
  src/components/payment/PaymentHistory.vue
  src/components/payment/PaymentHistoryItem.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/store/user/actions.js
  src/utils/plugins/i18n.js
  src/views/Profile.vue
Labels: enhancement, new feature

#785 Edited create intelligence components
  src/components/form-generator/FormGenerator.vue
  src/components/form-generator/inputs/TextInput.vue
  src/components/repository/CategorySelect.vue
  src/components/repository/CreateRepositoryForm.vue
  src/locales/en.json
  src/locales/pt_br.json
  test/unit/specs/components/form-generator/inputs/__snapshots__/TextInput.spec.js.snap
Labels: enhancement

#792 Fixed create repository forms
  src/components/repository/CreateRepositoryForm.vue
  test/unit/specs/components/repository/__snapshots__/CreateRepositoryForm.spec.js.snap
Labels: bug

#799 Added list total to pagination
  src/components/shared/PaginatedList.vue
  src/locales/en.json
  src/locales/pt_br.json
Labels: enhancement

#805 Edited some modals
  src/components/Tour.vue
  src/components/repository/CreateRepositoryForm.vue
  src/components/repository/RepositoryCard.vue
  src/components/repository/TrainModal.vue
  src/components/translate/NewTranslateForm.vue
  src/components/translate/TranslationsList.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Trainings.vue
  test/unit/specs/components/repository/__snapshots__/TrainModal.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/NewTranslateForm.spec.js.snap
Labels: enhancement

#814 New tutorial version
  src/api/tutorial.js
  src/components/Tour.vue
  src/components/TutorialModal.vue
  src/components/example/NewExampleForm.vue
  src/components/form-generator/inputs/FetchChoiceInput.vue
  src/components/inputs/EntitiesInput/EntitiesInput.vue
  src/components/inputs/EntitiesInput/EntityForm.vue
  src/components/quick-test/QuickTest.vue
  src/components/repository/CreateRepositoryForm.vue
  src/components/repository/IntentModal.vue
  src/components/repository/RequestGenerator.vue
  src/components/repository/TrainModal.vue
  src/components/repository/repository-evaluate/example/NewEvaluateExample.vue
  src/components/repository/repository-log/RepositoryLogList.vue
  src/components/shared/Layout.vue
  src/components/shared/accordion/LogAccordion.vue
  src/components/translate/NewTranslateForm.vue
  src/components/translate/TranslateExampleItem.vue
  src/layout/dashboard/DashboardLayout.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/store/tutorial/actions.js
  src/store/tutorial/getters.js
  src/store/tutorial/mutations.js
  src/store/tutorial/state.js
  src/views/Home.vue
  src/views/repository/Evaluate.vue
  src/views/repository/Integration.vue
  src/views/repository/Log.vue
  src/views/repository/Trainings.vue
  src/views/repository/Translate.vue
  test/unit/specs/components/example/__snapshots__/NewExampleForm.spec.js.snap
  test/unit/specs/components/quick-test/__snapshots__/QuickTest.spec.js.snap
  test/unit/specs/components/repository/__snapshots__/CreateRepositoryForm.spec.js.snap
  test/unit/specs/components/repository/__snapshots__/RequestGenerator.spec.js.snap
  test/unit/specs/components/repository/__snapshots__/TrainModal.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/NewEvaluateExample.spec.js.snap
  test/unit/specs/components/shared/__snapshots__/Layout.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/NewTranslateForm.spec.js.snap
  test/unit/specs/views/repository/__snapshots__/Evaluate.spec.js.snap
  test/unit/specs/views/repository/__snapshots__/Log.spec.js.snap
  test/unit/specs/views/repository/__snapshots__/Translate.spec.js.snap
Labels: enhancement
