Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-08, with the labels that each got.

#837 Edit summary content
  src/components/repository/SummaryInformation.vue
  src/layout/dashboard/DashboardLayout.vue
  src/models/repository.js
Labels: enhancement

#836 Edit/tutorial modal
  config/prod.env.js
  src/api/tutorial.js
  src/components/Tour.vue
  src/components/TutorialModal.vue
  src/components/example/NewExampleForm.vue
  src/components/repository/RepositoryCardList.vue
  src/components/repository/TrainModal.vue
  src/components/repository/repository-evaluate/example/NewEvaluateExample.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleItem.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/store/tutorial/actions.js
  src/views/Home.vue
  src/views/repository/Evaluate.vue
  test/unit/specs/components/example/__snapshots__/NewExampleForm.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/NewEvaluateExample.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleList.spec.js.snap
Labels: enhancement

#849 Bugfix/fix GitHub icon
  src/components/shared/SiteFooter.vue
  test/unit/specs/components/shared/__snapshots__/SiteFooter.spec.js.snap
Labels: bug

#862 Added support to new languages
  bh/dist/bh.js
  bh/src/utils.js
Labels: enhancement

#867 Edited sentencesList
  src/components/repository/SentencesEntityList.vue
  src/components/repository/SentencesIntentList.vue
Labels: enhancement

#869 Feature/create new texts feedbacks
  src/api/repository.js
  src/components/example/ExamplesList.vue
  src/components/quick-test/QuickTest.vue
  src/components/quick-test/QuickTestText.vue
  src/components/repository/AuthorizationItem.vue
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
  src/components/translate/TranslationsList.vue
  src/components/translate/TranslationsStatus.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/store/repository/actions.js
  src/views/repository/Trainings.vue
  src/views/repository/Translations.vue
  test/unit/specs/components/example/__snapshots__/ExamplesList.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/TranslationsList.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/TranslationsStatus.spec.js.snap
Labels: enhancement

#893 Fixed field spacing
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
Labels: bug

#894 Feature/master changes
  package.json
  yarn.lock
Labels: dependencies

#891 Added option to change versions on version list
  src/components/repository/RepositoryVersionList.vue
  src/locales/en.json
  src/locales/pt_br.json
Labels: bug

#892 Bugfix/hightlighted text
  src/components/example/NewExampleForm.vue
  src/components/inputs/EntitiesInput/EntitiesInput.vue
  src/components/inputs/EntitiesInput/EntityForm.vue
  src/components/inputs/ExampleTextWithHighlightedEntitiesInput.vue
  src/components/shared/HighlightedText.vue
  src/utils/index.js
  test/unit/specs/components/example/__snapshots__/NewExampleForm.spec.js.snap
  test/unit/specs/components/inputs/EntitiesInput/EntitiesInput.spec.js
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/NewEvaluateExample.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/NewTranslateForm.spec.js.snap
Labels: bug

#895 Bugfix/highlighted text size
  src/components/example/ExampleItem.vue
  src/components/quick-test/QuickTest.vue
  src/components/quick-test/QuickTestText.vue
  src/components/repository/SentencesEntityList.vue
  src/components/repository/SentencesIntentList.vue
  src/components/repository/repository-evaluate/example/EvaluateExampleList.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleItem.vue
  src/components/shared/HighlightedText.vue
  src/components/shared/accordion/ExampleAccordion.vue
  src/components/shared/accordion/LogAccordion.vue
  src/components/translate/TranslateExampleItem.vue
  src/components/translate/TranslationItem.vue
  src/components/translate/TranslationStatusInfo.vue
  test/unit/specs/components/shared/__snapshots__/HighlightedText.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/TranslateExampleItem.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/TranslationItem.spec.js.snap
Labels: bug

#896 Fixed crash with intent error
  src/components/repository/repository-evaluate/example/NewEvaluateExample.vue
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/NewEvaluateExample.spec.js.snap
Labels: bug
