Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-09, with the labels that each got.

#924 Fixed highlight text font being different
  src/components/inputs/ExampleTextWithHighlightedEntitiesInput.vue
  src/components/quick-test/QuickTestText.vue
  src/components/shared/HighlightedText.vue
  test/unit/specs/components/inputs/__snapshots__/ExampleTextWithHighlightedEntitiesInput.spec.js.snap
Labels: bug

#918 Feature/evaluate translation
  src/App.vue
  src/api/translate.js
  src/components/example/ExamplesList.vue
  src/components/example/ExamplesPendingTraining.vue
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
  src/components/shared/LanguageBadge.vue
  src/components/shared/accordion/EditExample.vue
  src/components/shared/accordion/EditExampleAccordion.vue
  src/components/shared/accordion/EditExampleBase.vue
  src/components/shared/accordion/EditExampleTranslation.vue
  src/components/shared/accordion/ExampleAccordion.vue
  src/components/shared/accordion/ExampleAccordionWithTranslations.vue
  src/components/shared/accordion/ExampleTranslation.vue
  src/components/shared/accordion/SentenceAccordion.vue
  src/components/translate/TranslateExampleItem.vue
  src/components/translate/TranslationItem.vue
  src/components/translate/TranslationsList.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/store/translate/actions.js
  src/utils/index.js
  src/views/repository/Trainings.vue
  test/unit/specs/components/example/__snapshots__/ExamplesList.spec.js.snap
  test/unit/specs/components/inputs/ExampleTextWithHighlightedEntitiesInput.spec.js
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleItem.spec.js.snap
  test/unit/specs/components/shared/__snapshots__/SentenceAccordion.spec.js.snap
  test/unit/specs/components/shared/accordion/ExampleAccordionWithTranslations.spec.js
  test/unit/specs/components/shared/accordion/__snapshots__/ExampleAccordionWithTranslations.spec.js.snap
  test/unit/specs/components/translate/__snapshots__/TranslationsList.spec.js.snap
Labels: enhancement

#937 Fixed intent list title
  src/locales/en.json
Labels: bug

#954 Feature/translation training
  src/components/repository/training/Train.vue
  src/components/repository/training/TrainModal.vue
  src/components/repository/training/TrainResponse.vue
  src/components/shared/PaginatedList.vue
  src/views/repository/Trainings.vue
  src/views/repository/Translate.vue
  test/unit/specs/components/repository/TrainModal.spec.js
  test/unit/specs/components/repository/TrainResponse.spec.js
  test/unit/specs/views/repository/__snapshots__/Translate.spec.js.snap
Labels: help wanted

#963 Fixed version not being passed on translate
  src/api/translate.js
  src/components/translate/NewTranslateExampleItem.vue
Labels: bug
