Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-03, with the labels that each got.

#468 Feature/quick test
  src/api/repository.js
  src/components/quick-test/QuickTest.vue
  src/components/repository/RepositoryViewBase/RepositoryViewBase.vue
  src/components/repository/debug/Debug.vue
  src/store/repository/actions.js
  src/utils/index.js
  src/views/repository/Log.vue
  test/unit/specs/components/repository/RepositoryViewBase/__snapshots__/RepositoryViewBase.spec.js.snap
Labels: enhancement

#477 [fix] Debug Parse Request
  src/components/repository/debug/Debug.vue
Labels: bug

#479 Added snapshot to QuickTest
  src/components/quick-test/QuickTest.vue
  src/components/repository/RepositoryViewBase/RepositoryViewBase.vue
  test/unit/specs/components/quick-test/QuickTest.spec.js
  test/unit/specs/components/quick-test/__snapshots__/QuickTest.spec.js.snap
Labels: enhancement

#480 component repositoryViewBase aligned to the center
  src/components/repository/RepositoryViewBase/RepositoryViewBase.vue
Labels: enhancement

#484 Training and test icons changed when wrapper
  src/components/repository/sidebar/SideBar.vue
Labels: enhancement

#481 Added language filter on training screen
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
  src/utils/index.js
  src/views/repository/Trainings.vue
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/FilterEvaluateExample.spec.js.snap
Labels: enhancement

#486 Feature/settings options bh
  bh/package.json
  bh/yarn.lock
  src/components/form-generator/FormGenerator.vue
  src/components/repository/EditRepositoryForm.vue
Labels: dependencies, enhancement

#482 Feature/sidebar-reformulation
  src/components/repository/sidebar/SideBar.vue
  src/layout/dashboard/DashboardLayout.vue
Labels: enhancement

#491 Added log tests
  src/components/shared/accordion/SentenceAccordion.vue
  test/unit/specs/components/shared/SentenceAccordion.spec.js
  test/unit/specs/components/shared/__snapshots__/SentenceAccordion.spec.js.snap
  test/unit/specs/views/repository/Log.spec.js
  test/unit/specs/views/repository/__snapshots__/Log.spec.js.snap
Labels: enhancement

#490 Bugfix/create bot form
  src/components/repository/NewRepositoryForm.vue
  src/components/shared/NewRepositoryModal.vue
  src/models/newRepository.js
Labels: bug

#489 Bugfix/log version name
  src/components/shared/accordion/LogAccordion.vue
  src/views/repository/Log.vue
  src/views/repository/Trainings.vue
Labels: bug

#496 Bugfix/debug colors
  src/components/inputs/TextAreaInput.vue
  src/components/quick-test/QuickTest.vue
  src/components/repository/debug/Debug.vue
  src/utils/index.js
  test/unit/specs/components/quick-test/__snapshots__/QuickTest.spec.js.snap
Labels: bug

#505 Feature/versions tests
  src/components/repository/RepositoryVersionList.vue
  src/views/repository/Log.vue
  src/views/repository/Versions.vue
  test/unit/specs/components/repository/RepositoryVersionList.spec.js
  test/unit/specs/components/repository/__snapshots__/RepositoryVersionList.spec.js.snap
Labels: enhancement

#495 Fixed example filter layout
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
Labels: bug

#494 Added translation status view to menu
  src/components/repository/sidebar/SideBar.vue
  src/locales/en.json
  src/locales/pt_br.json
  test/unit/specs/components/repository/sidebar/__snapshots__/SideBar.spec.js.snap
Labels: bug, enhancement

#503 Bugfix/version switching
  src/components/repository/RepositoryVersionList.vue
  src/layout/dashboard/DashboardLayout.vue
  src/layout/dashboard/VersionDropdown.vue
  src/store/repository/actions.js
  src/store/repository/getters.js
  src/store/repository/mutations.js
  src/store/repository/state.js
  test/unit/specs/components/layout/VersionDropdown.spec.js
  test/unit/specs/components/layout/__snapshots__/VersionDropdown.spec.js.snap
Labels: bug

#507 Fixed not being able to click behind quick test
  src/components/quick-test/QuickTest.vue
  src/layout/dashboard/DashboardLayout.vue
Labels: bug

#508 Bugfix/log translation edit
  src/components/repository/repository-log/RepositoryLogList.vue
  src/components/shared/PaginatedList.vue
  src/components/shared/accordion/EditExample.vue
  src/components/shared/accordion/LogAccordion.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Log.vue
  test/unit/specs/views/repository/Log.spec.js
  test/unit/specs/views/repository/__snapshots__/Log.spec.js.snap
Labels: enhancement

#506 Added intent modal
  src/api/example.js
  src/components/repository/IntentModal.vue
  src/components/shared/accordion/LogAccordion.vue
  src/locales/en.json
  src/locales/pt_br.json
Labels: enhancement

#516 [fix] i18n
  src/components/repository/IntentModal.vue
  src/components/repository/RepositoryHandleVersionModal.vue
  src/components/repository/debug/Debug.vue
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
  src/components/repository/repository-log/RepositoryLogList.vue
  src/components/shared/CategoriesList.vue
  src/components/shared/accordion/LogAccordion.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Log.vue
  src/views/repository/Result.vue
  src/views/repository/Results.vue
  test/unit/specs/components/shared/__snapshots__/CategoriesList.spec.js.snap
  test/unit/specs/views/repository/__snapshots__/Log.spec.js.snap
Labels: dependencies, enhancement

#518 Feature/fixed header
  src/components/repository/RepositoryViewBase/RepositoryViewBase.vue
  src/components/repository/sidebar/SideBar.vue
  src/layout/dashboard/DashboardLayout.vue
Labels: enhancement

#519 [fix] i18n translation
  src/components/repository/RequestAuthorizationModal.vue
  src/views/repository/Settings.vue
  src/views/repository/Trainings.vue
  src/views/repository/Translate.vue
  test/unit/specs/components/repository/__snapshots__/RequestAuthorizationModal.spec.js.snap
Labels: dependencies, enhancement

#520 Feature/missing translations
  src/components/repository/debug/Debug.vue
  src/components/repository/repository-evaluate/example/FilterEvaluateExample.vue
  src/components/shared/accordion/EditExample.vue
  src/components/translate/NewTranslateForm.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Evaluate.vue
  src/views/repository/Settings.vue
  test/unit/specs/components/translate/__snapshots__/NewTranslateForm.spec.js.snap
Labels: enhancement

#521 Bugfix/empty debug
  src/components/repository/debug/Debug.vue
Labels: bug, enhancement

#522 Bugfix/translation cards
  src/api/repository.js
  src/components/translate/TranslationsStatus.vue
  src/store/repository/actions.js
  src/views/repository/Translations.vue
  test/unit/specs/components/translate/__snapshots__/TranslationsStatus.spec.js.snap
Labels: bug

#524 Bugfix/integration text
  src/components/quick-test/QuickTest.vue
  src/views/repository/Integration.vue
Labels: bug

#527 Bugfix/sentence accordion
  src/components/shared/accordion/ExampleAccordion.vue
Labels: bug

#531 Fixed select option bug on intent modal
  src/components/repository/IntentModal.vue
Labels: bug

#538 Fixed repository version
  src/components/repository/TrainModal.vue
  src/components/repository/sidebar/SideBar.vue
  src/layout/dashboard/DashboardLayout.vue
  src/models/repository.js
  src/store/repository/getters.js
  src/store/repository/mutations.js
  src/views/repository/Trainings.vue
  test/unit/specs/components/repository/__snapshots__/TrainModal.spec.js.snap
  test/unit/specs/components/repository/sidebar/__snapshots__/SideBar.spec.js.snap
Labels: bug
