Repository Ilhasoft/bothub-webapp, pull requests merged in 2020-04, with the labels that each got.

#541 Fixed train intent bug
  src/components/repository/IntentModal.vue
Labels: bug

#540 Fixed quick test bug
  src/components/quick-test/QuickTest.vue
  test/unit/specs/components/quick-test/QuickTest.spec.js
  test/unit/specs/components/quick-test/__snapshots__/QuickTest.spec.js.snap
Labels: bug

#550 Added new inteligence permission
  src/components/inputs/RoleSelect.vue
  src/components/translate/TranslateExampleItem.vue
  src/utils/index.js
  src/views/repository/Translate.vue
Labels: enhancement

#544 Fixed inverted log notification
  src/components/shared/accordion/LogAccordion.vue
Labels: bug

#543 Fixed route error when try to add entity
  src/api/entity.js
Labels: bug

#557 Bugfix/training-page-refresh
  src/components/example/ExamplesList.vue
  src/views/repository/Trainings.vue
Labels: bug

#558 Feature/quick test entity
  src/components/quick-test/QuickTest.vue
  src/components/quick-test/QuickTestText.vue
  src/locales/en.json
  src/locales/pt_br.json
Labels: enhancement

#555 Fixed training response layout
  src/components/repository/TrainResponse.vue
  src/locales/en.json
  src/locales/pt_br.json
  test/unit/specs/components/repository/__snapshots__/TrainResponse.spec.js.snap
Labels: bug

#559 Added pagination to examples
  src/api/example.js
  src/api/repository.js
  src/api/repository.test.js
  src/api/translate.js
  src/api/user.js
  src/api/v2/evaluate-example.js
  src/components/MyProfile.vue
  src/components/example/ExamplesList.vue
  src/components/repository/AuthorizationRequestsList.vue
  src/components/repository/AuthorizationsList.vue
  src/components/repository/repository-evaluate/example/EvaluateExampleList.vue
  src/components/shared/PaginatedList.vue
  src/components/translate/TranslationsList.vue
  src/store/evaluate-example/actions.js
  src/store/example/actions.js
  src/store/repository/actions.js
  src/store/translate/actions.js
  src/store/user/actions.js
  test/unit/specs/components/example/ExamplesList.spec.js
  test/unit/specs/components/example/__snapshots__/ExamplesList.spec.js.snap
  test/unit/specs/components/repository/AuthorizationsList.spec.js
  test/unit/specs/components/repository/__snapshots__/AuthorizationRequestsList.spec.js.snap
  test/unit/specs/components/repository/__snapshots__/AuthorizationsList.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/example/EvaluateExampleList.spec.js
  test/unit/specs/components/repository/repository-evaluate/example/__snapshots__/EvaluateExampleList.spec.js.snap
  test/unit/specs/components/translate/TranslationsList.spec.js
  test/unit/specs/components/translate/__snapshots__/TranslationsList.spec.js.snap
Labels: enhancement

#561 Fixed repository uuid not being passed
  src/components/quick-test/QuickTest.vue
Labels: bug

#563 Bugfix/side bar modal
  src/layout/dashboard/DashboardLayout.vue
Labels: bug

#562 Fixed not finding words
  src/utils/index.js
Labels: bug

#565 Feature/version hide
  config/dev.env.js
  config/prod.env.js
  src/components/repository/sidebar/SideBar.vue
  src/layout/dashboard/DashboardLayout.vue
  src/router/index.js
  src/store/repository/getters.js
  src/views/repository/Versions.vue
  test/unit/specs/components/repository/sidebar/SideBar.spec.js
Labels: enhancement

#566 Fixed layout for entities
  src/components/quick-test/QuickTest.vue
  src/components/quick-test/QuickTestText.vue
Labels: bug

#567 Bugfix/translation example
  src/components/repository/RepositoryViewBase/RepositoryViewBase.vue
  src/components/shared/SideBar.vue
  src/components/shared/accordion/ExampleAccordion.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Evaluate.vue
  src/views/repository/Log.vue
  src/views/repository/Result.vue
  src/views/repository/Results.vue
  src/views/repository/Settings.vue
  src/views/repository/Trainings.vue
  src/views/repository/Translate.vue
Labels: bug

#579 Bugfix/translation version
  src/components/translate/TranslateList.vue
  src/store/example/actions.js
Labels: bug

#580 Bugfix/training status reload
  src/api/repository.js
  src/store/repository/actions.js
  src/views/repository/Trainings.vue
Labels: bug

#584 Added python and new env VERSION_ENABLED
  Dockerfile
Labels: bug, enhancement

#588 Fixed repository uuid not being passed
  src/components/quick-test/QuickTestText.vue
Labels: bug

#587 Fixed entity quick test layout
  src/components/quick-test/QuickTestText.vue
Labels: bug

#581 Feature/train modal translation
  src/components/repository/TrainModal.vue
  src/locales/en.json
  src/locales/pt_br.json
  test/unit/specs/components/repository/__snapshots__/TrainModal.spec.js.snap
Labels: enhancement

#589 Fixed repsitory sometimes not being fetched
  src/models/repository.js
Labels: bug

#590 Updating example count on training
  src/store/repository/actions.js
Labels: bug

#591 Put character limit on version name
  src/components/repository/RepositoryHandleVersionModal.vue
  src/components/repository/RepositoryVersionList.vue
Labels: enhancement

#592 Bugfix/quick test multiple entities
  src/components/quick-test/QuickTestText.vue
Labels: bug

#594 Updating only list on translation
  src/components/translate/TranslateExampleItem.vue
  src/components/translate/TranslateList.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Translate.vue
Labels: enhancement

#600 Bugfix/version id switching
  src/components/example/ExamplesList.vue
  src/components/example/NewExampleForm.vue
  src/components/quick-test/QuickTest.vue
  src/components/quick-test/QuickTestText.vue
  src/components/repository/AnalyzeTextDrawer.vue
  src/components/repository/RepositoryVersionList.vue
  src/components/repository/debug/Debug.vue
  src/components/repository/repository-evaluate/example/EvaluateExampleList.vue
  src/components/repository/repository-evaluate/example/NewEvaluateExample.vue
  src/components/translate/TranslateList.vue
  src/layout/dashboard/DashboardLayout.vue
  src/layout/dashboard/VersionDropdown.vue
  src/models/repository.js
  src/store/repository/getters.js
  src/store/repository/mutations.js
  src/views/repository/Base.vue
  src/views/repository/Evaluate.vue
  src/views/repository/Result.vue
  src/views/repository/Results.vue
Labels: bug, help wanted

#607 Sending version on log sentence add
  src/components/repository/repository-log/RepositoryLogList.vue
Labels: bug

#606 Bugfix/version cache
  src/models/base.js
  src/models/repository.js
  src/store/cached-fetch/mutations.js
  src/store/repository/mutations.js
  src/views/repository/Base.vue
Labels: bug, help wanted

#614 Bugfix/results translation
  src/components/repository/repository-evaluate/results/EvaluateResultExampleItem.vue
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
  src/components/repository/repository-evaluate/results/GraphicsResult.vue
  src/components/repository/repository-evaluate/versions/EvaluateVersionItem.vue
  src/locales/en.json
  src/locales/pt_br.json
  src/views/repository/Result.vue
  src/views/repository/Results.vue
  test/unit/specs/components/repository/repository-evaluate/results/EvaluateResultExampleItem.spec.js
  test/unit/specs/components/repository/repository-evaluate/results/EvaluateResultExampleList.spec.js
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleItem.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleList.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/GraphicsResult.spec.js.snap
  test/unit/specs/components/repository/repository-evaluate/versions/EvaluateVersionItem.spec.js
  test/unit/specs/components/repository/repository-evaluate/versions/__snapshots__/EvaluateVersionItem.spec.js.snap
Labels: bug

#616 Feature/results pagination
  package.json
  src/api/v2/evaluate-example.js
  src/components/repository/repository-evaluate/results/EvaluateResultExampleList.vue
  src/components/repository/repository-evaluate/versions/EvaluateVersionList.vue
  src/store/evaluate-example/actions.js
  test/unit/specs/components/repository/repository-evaluate/results/__snapshots__/EvaluateResultExampleList.spec.js.snap
Labels: enhancement
